version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.8-jdk
    steps:
      - checkout
      - run: ./gradlew test sonarqube

workflows:
  app:
    jobs:
      - build:
          context:
            - sonar-secrets
