version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.8-jdk
    steps:
      - checkout
      - run: ./gradlew test

  lint:
    docker:
      - image: circleci/openjdk:11.0.8-jdk
    steps:
      - checkout
      - run: ./gradlew sonarqube

workflows:
  app:
    jobs:
      - build
      - lint:
          requires: [build]
          context:
            - sonar-secrets
