version: 2.1

orbs:
  slack: circleci/slack@4.3.1

commands:

  slack-notify-fail:
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1

  slack-notify-pass:
    steps:
      - slack/notify:
          event: pass
          template: basic_success_1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.8-jdk
    steps:
      - checkout
      - run: ./gradlew build test sonarqube
      - slack-notify-fail

workflows:
  app:
    jobs:
      - build:
          context:
            - sonar-secrets
            - slack-secrets
