apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - port: {{ .Values.service.port.value }}
      targetPort: {{ .Values.app.portName }}
      name: {{ .Values.service.port.name | trunc 15 }}
